DROP TABLE IF EXISTS CART;
CREATE TABLE CART (
    CART_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CART_DESCRIPTION VARCHAR NOT NULL,
    USER_ID INT NOT NULL
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT(
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_DESCRIPTION VARCHAR NOT NULL
);

DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM (
    ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_QUANTITY INT NOT NULL DEFAULT 0,

    CART_ID BIGINT NOT NULL,
    foreign key(CART_ID) references CART(CART_ID),

    PRODUCT_ID BIGINT NOT NULL,
    foreign key(PRODUCT_ID) references PRODUCT(PRODUCT_ID)
);

